language: php

php:
  - 5.4
  - 5.5

env:
  - CAKE_VERSION=2.3.10 DB=mysql
  - CAKE_VERSION=2.4.10 DB=mysql
  - CAKE_VERSION=master DB=mysql

install:
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp && git checkout $CAKE_VERSION
  - cp -R ../app_description plugins/AppDescription
  - chmod -R 777 ../cakephp/app/tmp
  - sh -c "composer global require 'phpunit/phpunit=3.7.33'"
  - sh -c "ln -s ~/.composer/vendor/phpunit/phpunit/PHPUnit ../cakephp/vendors/PHPUnit"

before_script:
  - sh -c "mysql -e 'CREATE DATABASE cakephp_test;'"
  - set +H
  - echo "<?php
    class DATABASE_CONFIG {
    public \$default = array(
      'persistent' => false,
      'host' => '0.0.0.0',
      'login' => 'travis',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => ''
    );
    public \$test = array(
      'persistent' => false,
      'host' => '0.0.0.0',
      'login' => 'travis',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => ''
    );
    }" > ../cakephp/app/Config/database.php

script:
  - ./lib/Cake/Console/cake test AppDescription AllAppDescription --stderr

notifications:
  email: false
